#!/usr/bin/env bash
set -euo pipefail

AGENT_NAME="${AGENT_NAME:-langchainoa}"
LOCATION="${LOCATION:-malaysiawest}"
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-agent365-${AGENT_NAME}-${LOCATION}}"
APP_NAME="${APP_NAME:-${AGENT_NAME}}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$PROJECT_DIR/.env}"
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"

[[ -f "$ENV_FILE" ]] || { echo "ERROR: $ENV_FILE not found; run a365 setup all first." >&2; exit 1; }

read_value() {
  local key="$1"
  sed -n "s/^${key}=//p" "$ENV_FILE" | tail -1
}

SERVICE_CLIENT_ID="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID)"
SERVICE_CLIENT_SECRET="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET)"
SERVICE_TENANT_ID="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID)"
SERVICE_SCOPES="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__SCOPES)"
AGENTIC_TYPE="$(read_value AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__TYPE)"
AGENTIC_ALT_BLUEPRINT="$(read_value AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__ALT_BLUEPRINT_NAME)"
AGENTIC_SCOPES="$(read_value AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__SCOPES)"
CONNECTION_URL="$(read_value CONNECTIONSMAP__0__SERVICEURL)"
CONNECTION_NAME="$(read_value CONNECTIONSMAP__0__CONNECTION)"
OBS_TENANT_ID="$(read_value AGENT365OBSERVABILITY__TENANTID)"
OBS_BLUEPRINT_ID="$(read_value AGENT365OBSERVABILITY__AGENTBLUEPRINTID)"

for required in SERVICE_CLIENT_ID SERVICE_CLIENT_SECRET SERVICE_TENANT_ID AGENTIC_TYPE; do
  [[ -n "${!required}" ]] || { echo "ERROR: $required is empty in $ENV_FILE" >&2; exit 1; }
done

az containerapp secret set --subscription "$SUBSCRIPTION_ID" \
  -g "$RESOURCE_GROUP" -n "$APP_NAME" \
  --secrets "service-connection-secret=$SERVICE_CLIENT_SECRET" -o none

az containerapp update --subscription "$SUBSCRIPTION_ID" \
  -g "$RESOURCE_GROUP" -n "$APP_NAME" \
  --set-env-vars \
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID=$SERVICE_CLIENT_ID" \
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET=secretref:service-connection-secret" \
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID=$SERVICE_TENANT_ID" \
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__SCOPES=$SERVICE_SCOPES" \
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__TYPE=$AGENTIC_TYPE" \
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__ALT_BLUEPRINT_NAME=$AGENTIC_ALT_BLUEPRINT" \
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__SCOPES=$AGENTIC_SCOPES" \
    "CONNECTIONSMAP__0__SERVICEURL=${CONNECTION_URL:-*}" \
    "CONNECTIONSMAP__0__CONNECTION=${CONNECTION_NAME:-SERVICE_CONNECTION}" \
    "AUTH_HANDLER_NAME=AGENTIC" \
    "TENANT_ID=$SERVICE_TENANT_ID" \
    "BLUEPRINT_APP_ID=$SERVICE_CLIENT_ID" \
    "AGENT365OBSERVABILITY__TENANTID=${OBS_TENANT_ID:-$SERVICE_TENANT_ID}" \
    "AGENT365OBSERVABILITY__AGENTBLUEPRINTID=${OBS_BLUEPRINT_ID:-$SERVICE_CLIENT_ID}" \
    "ENABLE_A365_OBSERVABILITY=true" \
    "ENABLE_A365_OBSERVABILITY_EXPORTER=true" \
    -o none

echo "Agent 365 settings synchronized to $RESOURCE_GROUP/$APP_NAME."