#!/usr/bin/env bash
set -euo pipefail

AGENT_NAME="${AGENT_NAME:-langchainoa}"
LOCATION="${LOCATION:-}"
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-agent365-${AGENT_NAME}-${LOCATION}}"
APP_NAME="${APP_NAME:-${AGENT_NAME}}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$PROJECT_DIR/.env}"
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"

[[ -n "$LOCATION" ]] || { echo "ERROR: LOCATION is required" >&2; exit 1; }
[[ -f "$ENV_FILE" ]] || { echo "ERROR: $ENV_FILE not found; run a365 setup all first." >&2; exit 1; }

read_value() {
  local key="$1"
  sed -n "s/^${key}=//p" "$ENV_FILE" | tail -1
}

SERVICE_CLIENT_ID="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID)"
SERVICE_CLIENT_SECRET="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET)"
SERVICE_AUTH_TYPE="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__AUTHTYPE)"
SERVICE_AUTH_TYPE="${SERVICE_AUTH_TYPE:-ClientSecret}"
SERVICE_FEDERATED_CLIENT_ID="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__FEDERATEDCLIENTID)"
SERVICE_TENANT_ID="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID)"
SERVICE_SCOPES="$(read_value CONNECTIONS__SERVICE_CONNECTION__SETTINGS__SCOPES)"
AGENTIC_TYPE="$(read_value AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__TYPE)"
AGENTIC_ALT_BLUEPRINT="$(read_value AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__ALT_BLUEPRINT_NAME)"
AGENTIC_SCOPES="$(read_value AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__SCOPES)"
CONNECTION_URL="$(read_value CONNECTIONSMAP__0__SERVICEURL)"
CONNECTION_NAME="$(read_value CONNECTIONSMAP__0__CONNECTION)"
OBS_TENANT_ID="$(read_value AGENT365OBSERVABILITY__TENANTID)"
OBS_BLUEPRINT_ID="$(read_value AGENT365OBSERVABILITY__AGENTBLUEPRINTID)"

for required in SERVICE_CLIENT_ID SERVICE_TENANT_ID AGENTIC_TYPE; do
  [[ -n "${!required}" ]] || { echo "ERROR: $required is empty in $ENV_FILE" >&2; exit 1; }
done

# FederatedCredentials (see enable-federated-credentials.sh) keeps the app keyless;
# ClientSecret stores the Blueprint secret as a Container App secret reference.
if [[ "$SERVICE_AUTH_TYPE" == "FederatedCredentials" ]]; then
  [[ -n "$SERVICE_FEDERATED_CLIENT_ID" ]] || { echo "ERROR: FEDERATEDCLIENTID is empty in $ENV_FILE" >&2; exit 1; }
  AUTH_ENV=(
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__AUTHTYPE=FederatedCredentials"
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__FEDERATEDCLIENTID=$SERVICE_FEDERATED_CLIENT_ID"
  )
  REMOVE_ENV=(--remove-env-vars "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET")
else
  [[ -n "$SERVICE_CLIENT_SECRET" ]] || { echo "ERROR: SERVICE_CLIENT_SECRET is empty in $ENV_FILE" >&2; exit 1; }
  az containerapp secret set --subscription "$SUBSCRIPTION_ID" \
    -g "$RESOURCE_GROUP" -n "$APP_NAME" \
    --secrets "service-connection-secret=$SERVICE_CLIENT_SECRET" -o none
  AUTH_ENV=(
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__AUTHTYPE=ClientSecret"
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET=secretref:service-connection-secret"
  )
  REMOVE_ENV=()
fi

az containerapp update --subscription "$SUBSCRIPTION_ID" \
  -g "$RESOURCE_GROUP" -n "$APP_NAME" \
  --set-env-vars \
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID=$SERVICE_CLIENT_ID" \
    "${AUTH_ENV[@]}" \
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID=$SERVICE_TENANT_ID" \
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__SCOPES=$SERVICE_SCOPES" \
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__TYPE=$AGENTIC_TYPE" \
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__ALT_BLUEPRINT_NAME=$AGENTIC_ALT_BLUEPRINT" \
    "AGENTAPPLICATION__USERAUTHORIZATION__HANDLERS__AGENTIC__SETTINGS__SCOPES=$AGENTIC_SCOPES" \
    "CONNECTIONSMAP__0__SERVICEURL=${CONNECTION_URL:-*}" \
    "CONNECTIONSMAP__0__CONNECTION=${CONNECTION_NAME:-SERVICE_CONNECTION}" \
    "AUTH_HANDLER_NAME=AGENTIC" \
    "TENANT_ID=$SERVICE_TENANT_ID" \
    "BLUEPRINT_APP_ID=$SERVICE_CLIENT_ID" \
    "AGENT365OBSERVABILITY__TENANTID=${OBS_TENANT_ID:-$SERVICE_TENANT_ID}" \
    "AGENT365OBSERVABILITY__AGENTBLUEPRINTID=${OBS_BLUEPRINT_ID:-$SERVICE_CLIENT_ID}" \
    "ENABLE_A365_OBSERVABILITY=true" \
    "ENABLE_A365_OBSERVABILITY_EXPORTER=true" \
    ${REMOVE_ENV[@]+"${REMOVE_ENV[@]}"} \
    -o none

echo "Agent 365 settings synchronized to $RESOURCE_GROUP/$APP_NAME."